name: winplacearena
region: ams

services:
  - name: api
    github:
      repo: grinevoleg/winplacearena
      branch: main
      deploy_on_push: true
    source_dir: backend
    build_command: pip install --user -r requirements.txt
    run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
    routes:
      - path: /
    envs:
      - key: PORT
        scope: RUN_TIME
        value: "8000"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${arena-db.DATABASE_URL}
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ${api.PUBLIC_URL}

databases:
  - name: arena-db
    engine: PG
    version: "15"
    production: false
    db_name: arena
    db_user: arena_user
