name: winplacearena
region: ams

# Frontend Web Service (включает Next.js API routes)
services:
  - name: web
    github:
      repo: grinevoleg/winplacearena
      branch: main
      deploy_on_push: true
    source_dir: .
    build_command: npm install && NODE_ENV=production npm run build
    run_command: npm start
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: PORT
        scope: RUN_TIME
        value: "8080"

databases:
  - name: arena-db
    engine: PG
    version: "15"
    production: false
    db_name: arena
    db_user: arena_user
