name: winplacearena
region: ams

services:
  - name: api
    github:
      repo: grinevoleg/winplacearena
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: Dockerfile
    build_command: |
      cp -r ../frontend ./frontend || echo "Frontend not found, skipping"
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${arena-db.DATABASE_URL}
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ${api.PUBLIC_URL}

databases:
  - name: arena-db
    engine: PG
    version: "15"
    production: false
    db_name: arena
    db_user: arena_user
